language: ruby
sudo: required
rvm: 2.4
addons:
  chrome: stable
script:
  - bundle exec jekyll build
  - bundle exec rake wax:test
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  except:
    - gh-pages
