# basic settings
title: The Biggert Collection of Architectural Vignettes
description: The Biggert Collection of Architectural Vignettes on Commercial Stationery
baseurl: ''
url: ''
gh-baseurl: '/biggert_static'

# build settings
markdown: kramdown
theme: minima
exclude: [Gemfile*, vendor, Rakefile, README.md, wax_tasks]
permalink: pretty

# wax collection settings
collections:
  biggert:
    source: biggert-items.json
    layout: iiif-image-page
    output: true
    lunr_index:
      fields:
        - date_other
        - sort_title
        - title
        - subject_hierarchical_geographic
        - subject_name
        - genre
        - coordinates
        - call_number
        - doi

# cors headers for iiif use
webrick:
  headers:
    "Access-Control-Allow-Origin": "*"
